### ISSUE TITLE
NoScript Usability Impacts + Possible Support?

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-ux#43]
## The Problem
SecureDrop users need to be able to setup their Tor Browser & bundled tools, correctly, to protect themselves in advance of submitting sensitive documents. 

Access to NoScript's settings and subsequent comprehension of how to do what, are currently very difficult. Especially for non-technical users with usability expectations set by modern consumer software—which is the majority of our Source users, whom are only using SecureDrop to share information they're risking their own safety to share, with journalists.

## Background
Many of our Source Users are not "regular" Tor users, or users of any FOSS tools—for that matter. Most are entirely new to concepts of opsec and infosec, and expect (cough, need) usability to high consumer-product standards. NoScript of course, provides an utility that delivers substantial value and protections to our (and millions of other) users—for which all of us are very, very grateful. :)

To enable our Source and Journalist Users to best protect themselves, we've partnered with Tor and other teams to suggest and help with some basic usability improvements in products whose experiences overlap with SecureDrop. In recent days, we've encountered a bug that involves the NoScript settings. 

This bug (which can be traced to a Mozilla upstream issue) has put NoScript's usability concerns back on our radar. With that, I'd love to extend an invitation to @﻿hackademix to potentially work together on how we might be able to help NoScript with UX solutions? Not sure if @SimplySecure has engaged with NoScript, so cc'ing @BumbleBlue here just in case.

**Comment by hackademix** [comment]
I'm currently trying to help Mozilla fix the specific upload bug that you reference above in the WebExtensions API, since there's no work-around that can be implemented in NoScript other than bluntly turning off the XSS filter, or for the affected websites to use AJAX rather than HTML form submission.

Regarding the more general issue of UX enhancements, @simplysecure will start working on NoScript in April, as soon as the Cross-Browser NoScript project is wrapped up. I'd love to incorporate your ideas and contributions in that work as much as possible, so keep them coming. 

Thank you.

**Comment by ninavizz** [comment]
My offer is but a Toyota Corolla; SimplySecure are a Rolls Royce, with driver and fully-stoked bar. I close thee issue, beaming with hope and delight!

**Comment by bumbleblue** [comment]
@ninavizz Yes! We'll be working with NoScript starting this April, and would love to hear more about other tools that depend on NoScript for usability. If you have specific issues/ideas/suggestions, let us know 😃
